"""Intake ledger, raw capture, and replay semantics."""

from __future__ import annotations

from lark_to_notes.intake.ledger import (
    chat_ingest_key,
    chat_intake_ledger_counts,
    count_raw_messages,
    document_ingest_key,
    finish_intake_run,
    get_chat_intake_item,
    get_document_intake_item,
    get_raw_message,
    insert_raw_message,
    list_raw_messages,
    list_raw_messages_recent,
    list_ready_chat_intake,
    list_ready_document_intake,
    mark_chat_intake_processed,
    mark_document_intake_processed,
    observe_chat_message,
    observe_document_surface,
    start_intake_run,
)
from lark_to_notes.intake.models import (
    ChatEventAction,
    ChatIntakeItem,
    ChatIntakeState,
    DocumentIntakeItem,
    DocumentLifecycleState,
    DocumentRecordType,
    IntakePath,
    RawMessage,
)
from lark_to_notes.intake.reaction_caps import (
    REACTION_INTAKE_GOVERNANCE_VERSION,
    REACTION_INTAKE_POLICY_VERSION,
    ReactionIntakeCaps,
    ReactionIntakeCapState,
    reaction_cap_block_reason,
)
from lark_to_notes.intake.reaction_deferrals import (
    ReactionPipelineDoctorStatus,
    classify_reaction_pipeline_doctor_status,
    count_reaction_intake_deferrals,
    insert_reaction_intake_deferral,
    reaction_intake_deferral_metrics,
)
from lark_to_notes.intake.reaction_effective import (
    apply_reaction_step,
    effective_reaction_set_fingerprint,
    materialize_effective_counts,
)
from lark_to_notes.intake.reaction_model import (
    NormalizedReactionEvent,
    ReactionKind,
    parse_reaction_envelope,
    reaction_event_id_from_envelope,
    reaction_event_type,
)
from lark_to_notes.intake.reaction_store import (
    ReactionInsertResult,
    canonical_reaction_event_id,
    count_reaction_orphan_queue,
    insert_message_reaction_event,
    latest_message_reaction_event_seen_at,
    reaction_attach_reconcile_latency_ms,
    reaction_correlation_counts,
    reaction_ledger_governance_sample_for_doctor,
    reaction_orphan_backlog_metrics,
    surrogate_reaction_event_id,
)

__all__ = [
    "REACTION_INTAKE_GOVERNANCE_VERSION",
    "REACTION_INTAKE_POLICY_VERSION",
    "ChatEventAction",
    "ChatIntakeItem",
    "ChatIntakeState",
    "DocumentIntakeItem",
    "DocumentLifecycleState",
    "DocumentRecordType",
    "IntakePath",
    "NormalizedReactionEvent",
    "RawMessage",
    "ReactionInsertResult",
    "ReactionIntakeCapState",
    "ReactionIntakeCaps",
    "ReactionKind",
    "ReactionPipelineDoctorStatus",
    "apply_reaction_step",
    "canonical_reaction_event_id",
    "chat_ingest_key",
    "chat_intake_ledger_counts",
    "classify_reaction_pipeline_doctor_status",
    "count_raw_messages",
    "count_reaction_intake_deferrals",
    "count_reaction_orphan_queue",
    "document_ingest_key",
    "effective_reaction_set_fingerprint",
    "finish_intake_run",
    "get_chat_intake_item",
    "get_document_intake_item",
    "get_raw_message",
    "insert_message_reaction_event",
    "insert_raw_message",
    "insert_reaction_intake_deferral",
    "latest_message_reaction_event_seen_at",
    "list_raw_messages",
    "list_raw_messages_recent",
    "list_ready_chat_intake",
    "list_ready_document_intake",
    "mark_chat_intake_processed",
    "mark_document_intake_processed",
    "materialize_effective_counts",
    "observe_chat_message",
    "observe_document_surface",
    "parse_reaction_envelope",
    "reaction_attach_reconcile_latency_ms",
    "reaction_cap_block_reason",
    "reaction_correlation_counts",
    "reaction_event_id_from_envelope",
    "reaction_event_type",
    "reaction_intake_deferral_metrics",
    "reaction_ledger_governance_sample_for_doctor",
    "reaction_orphan_backlog_metrics",
    "start_intake_run",
    "surrogate_reaction_event_id",
]
